// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RiceMillApi.Data;

#nullable disable

namespace RiceMillApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304175650_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RiceMillApi.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentAccountId")
                        .HasColumnType("integer");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountCode")
                        .IsUnique();

                    b.HasIndex("ParentAccountId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccountCode = "1",
                            AccountName = "Land",
                            AccountType = "Asset",
                            Category = "Fixed Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(8930),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 2,
                            AccountCode = "2",
                            AccountName = "Building",
                            AccountType = "Asset",
                            Category = "Fixed Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(8933),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 3,
                            AccountCode = "3",
                            AccountName = "Furniture",
                            AccountType = "Asset",
                            Category = "Fixed Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(8936),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 4,
                            AccountCode = "4",
                            AccountName = "Machinery",
                            AccountType = "Asset",
                            Category = "Fixed Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(8938),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 5,
                            AccountCode = "5",
                            AccountName = "Vehicles",
                            AccountType = "Asset",
                            Category = "Fixed Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(8940),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 6,
                            AccountCode = "6",
                            AccountName = "Purchase",
                            AccountType = "Expense",
                            Category = "Direct Cost",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(8942),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 7,
                            AccountCode = "7",
                            AccountName = "Sales",
                            AccountType = "Income",
                            Category = "Revenue",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(8944),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 8,
                            AccountCode = "8",
                            AccountName = "Other Income",
                            AccountType = "Income",
                            Category = "Other Income",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(8946),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 9,
                            AccountCode = "10",
                            AccountName = "Administrative Expenses",
                            AccountType = "Expense",
                            Category = "Indirect Expense",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(8948),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 10,
                            AccountCode = "11",
                            AccountName = "Selling & Distribution Exp",
                            AccountType = "Expense",
                            Category = "Indirect Expense",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(8950),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 11,
                            AccountCode = "12",
                            AccountName = "Financial Expense",
                            AccountType = "Expense",
                            Category = "Financial",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(8952),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 12,
                            AccountCode = "13",
                            AccountName = "General Expense",
                            AccountType = "Expense",
                            Category = "Indirect Expense",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(8954),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 13,
                            AccountCode = "14",
                            AccountName = "Production Expense",
                            AccountType = "Expense",
                            Category = "Direct Cost",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(8962),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 14,
                            AccountCode = "15.1",
                            AccountName = "Debtor 1",
                            AccountType = "Asset",
                            Category = "Current Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(8964),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 15,
                            AccountCode = "15.2",
                            AccountName = "Debtor 2",
                            AccountType = "Asset",
                            Category = "Current Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9012),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 16,
                            AccountCode = "15.3",
                            AccountName = "Debtor 3",
                            AccountType = "Asset",
                            Category = "Current Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9014),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 17,
                            AccountCode = "15.4",
                            AccountName = "Debtor 4",
                            AccountType = "Asset",
                            Category = "Current Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9016),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 18,
                            AccountCode = "15.5",
                            AccountName = "Debtor 5",
                            AccountType = "Asset",
                            Category = "Current Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9018),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 19,
                            AccountCode = "15.6",
                            AccountName = "Debtor 6",
                            AccountType = "Asset",
                            Category = "Current Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9020),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 20,
                            AccountCode = "15.7",
                            AccountName = "Debtor 7",
                            AccountType = "Asset",
                            Category = "Current Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9022),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 21,
                            AccountCode = "15.8",
                            AccountName = "Debtor 8",
                            AccountType = "Asset",
                            Category = "Current Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9024),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 22,
                            AccountCode = "15.9",
                            AccountName = "Debtor 9",
                            AccountType = "Asset",
                            Category = "Current Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9026),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 23,
                            AccountCode = "16.1.1",
                            AccountName = "Paddy Creditors",
                            AccountType = "Liability",
                            Category = "Current Liability",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9028),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 24,
                            AccountCode = "16.1.2",
                            AccountName = "Other Creditors",
                            AccountType = "Liability",
                            Category = "Current Liability",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9030),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 25,
                            AccountCode = "16.1.3",
                            AccountName = "Financial Creditors",
                            AccountType = "Liability",
                            Category = "Current Liability",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9032),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 26,
                            AccountCode = "16.2",
                            AccountName = "Bank Long-Term Loan",
                            AccountType = "Liability",
                            Category = "Long-Term Liability",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9034),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 27,
                            AccountCode = "17.1",
                            AccountName = "Bank - Current Account",
                            AccountType = "Asset",
                            Category = "Current Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9035),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 28,
                            AccountCode = "17.2",
                            AccountName = "Bank - Saving Account",
                            AccountType = "Asset",
                            Category = "Current Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9037),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 29,
                            AccountCode = "18.1",
                            AccountName = "Salary Advance",
                            AccountType = "Asset",
                            Category = "Current Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9039),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 30,
                            AccountCode = "18.2",
                            AccountName = "Paddy Purchase Advance",
                            AccountType = "Asset",
                            Category = "Current Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9041),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 31,
                            AccountCode = "19",
                            AccountName = "Insurance",
                            AccountType = "Asset",
                            Category = "Prepaid",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9043),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 32,
                            AccountCode = "20",
                            AccountName = "Fixed Deposit",
                            AccountType = "Asset",
                            Category = "Current Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9045),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 33,
                            AccountCode = "21",
                            AccountName = "Lease",
                            AccountType = "Asset",
                            Category = "Long-Term",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9047),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 34,
                            AccountCode = "22",
                            AccountName = "Miscellaneous Account",
                            AccountType = "Expense",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9049),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 35,
                            AccountCode = "23",
                            AccountName = "Post-Dated Cheque",
                            AccountType = "Asset",
                            Category = "Current Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9051),
                            IsActive = true
                        },
                        new
                        {
                            AccountId = 36,
                            AccountCode = "24",
                            AccountName = "Cash",
                            AccountType = "Asset",
                            Category = "Current Asset",
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 500, DateTimeKind.Utc).AddTicks(9052),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("RiceMillApi.Models.Cheque", b =>
                {
                    b.Property<int>("ChequeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChequeId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("ChequeDate")
                        .HasColumnType("date");

                    b.Property<string>("ChequeNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ChequeType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateOnly?>("ClearedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPostDated")
                        .HasColumnType("boolean");

                    b.Property<int>("PartyId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending");

                    b.HasKey("ChequeId");

                    b.HasIndex("PartyId");

                    b.ToTable("Cheques");
                });

            modelBuilder.Entity("RiceMillApi.Models.FiscalYear", b =>
                {
                    b.Property<int>("FiscalYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FiscalYearId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("YearLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("FiscalYearId");

                    b.ToTable("FiscalYears");

                    b.HasData(
                        new
                        {
                            FiscalYearId = 1,
                            EndDate = new DateOnly(2025, 3, 31),
                            IsClosed = false,
                            StartDate = new DateOnly(2024, 4, 1),
                            YearLabel = "2024-2025"
                        });
                });

            modelBuilder.Entity("RiceMillApi.Models.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartyId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("LinkedAccountId")
                        .HasColumnType("integer");

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("OpeningBalanceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValue("DR");

                    b.Property<string>("PartyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("PartyId");

                    b.HasIndex("LinkedAccountId");

                    b.HasIndex("PartyCode")
                        .IsUnique();

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("RiceMillApi.Models.Transaction", b =>
                {
                    b.Property<int>("TxnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TxnId"));

                    b.Property<int?>("ChequeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("Narration")
                        .HasColumnType("text");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<int?>("PartyId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("cash");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateOnly>("TxnDate")
                        .HasColumnType("date");

                    b.Property<string>("TxnNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TxnType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("TxnId");

                    b.HasIndex("ChequeId")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FiscalYearId");

                    b.HasIndex("PartyId");

                    b.HasIndex("TxnNumber")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("RiceMillApi.Models.TransactionEntry", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntryId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CrAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal>("DrAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("Narration")
                        .HasColumnType("text");

                    b.Property<int?>("PartyId")
                        .HasColumnType("integer");

                    b.Property<int>("TxnId")
                        .HasColumnType("integer");

                    b.HasKey("EntryId");

                    b.HasIndex("AccountId");

                    b.HasIndex("PartyId");

                    b.HasIndex("TxnId");

                    b.ToTable("TransactionEntries");
                });

            modelBuilder.Entity("RiceMillApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("accountant");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 3, 4, 17, 56, 49, 656, DateTimeKind.Utc).AddTicks(4431),
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$8qEFXMNtPPiOhH55F.VQFOXVb1ELWkSQtYdZNMCPMd3y6Zar3NGC6",
                            Role = "admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("RiceMillApi.Models.Account", b =>
                {
                    b.HasOne("RiceMillApi.Models.Account", "ParentAccount")
                        .WithMany("SubAccounts")
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentAccount");
                });

            modelBuilder.Entity("RiceMillApi.Models.Cheque", b =>
                {
                    b.HasOne("RiceMillApi.Models.Party", "Party")
                        .WithMany("Cheques")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("RiceMillApi.Models.Party", b =>
                {
                    b.HasOne("RiceMillApi.Models.Account", "LinkedAccount")
                        .WithMany()
                        .HasForeignKey("LinkedAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LinkedAccount");
                });

            modelBuilder.Entity("RiceMillApi.Models.Transaction", b =>
                {
                    b.HasOne("RiceMillApi.Models.Cheque", "Cheque")
                        .WithOne("Transaction")
                        .HasForeignKey("RiceMillApi.Models.Transaction", "ChequeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RiceMillApi.Models.User", "CreatedByUser")
                        .WithMany("Transactions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RiceMillApi.Models.FiscalYear", "FiscalYear")
                        .WithMany("Transactions")
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RiceMillApi.Models.Party", "Party")
                        .WithMany("Transactions")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cheque");

                    b.Navigation("CreatedByUser");

                    b.Navigation("FiscalYear");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("RiceMillApi.Models.TransactionEntry", b =>
                {
                    b.HasOne("RiceMillApi.Models.Account", "Account")
                        .WithMany("TransactionEntries")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RiceMillApi.Models.Party", "Party")
                        .WithMany("TransactionEntries")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RiceMillApi.Models.Transaction", "Transaction")
                        .WithMany("Entries")
                        .HasForeignKey("TxnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Party");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("RiceMillApi.Models.Account", b =>
                {
                    b.Navigation("SubAccounts");

                    b.Navigation("TransactionEntries");
                });

            modelBuilder.Entity("RiceMillApi.Models.Cheque", b =>
                {
                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("RiceMillApi.Models.FiscalYear", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("RiceMillApi.Models.Party", b =>
                {
                    b.Navigation("Cheques");

                    b.Navigation("TransactionEntries");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("RiceMillApi.Models.Transaction", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("RiceMillApi.Models.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
